spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/todo_api
    username: postgres
    password: mysecretpassword

  application:
    name: todoApi
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
